### ISSUE TITLE
well-formed-html-document-lab..not passing with this code

### ISSUE THREAD

**Issue by daniel-unger** [learn-co-curriculum/well-formed-html-document-lab#1]
<!DOCTYPE html>
<html>
<head>
  <title>
  </title>
<body>

</body>

</head>

</html>

**Comment by aviflombaum** [comment]
That isn't the entire solution, so I'm not sure exactly what you meant. This is the solution https://github.com/learn-co-curriculum/well-formed-html-document-lab/blob/solution/index.html
