### ISSUE TITLE
Quick Fix Typo: Extra word "the" or "this"

### ISSUE THREAD

**Issue by ccklight** [learn-co-curriculum/well-formed-html-document-lab#12]
Line 2: Remove either "the" or "this" 
********************
Task #3 Add opening and closing head and body tags inside of the outer html tags.

You can run the tests for this lab via learn. Make sure you save the file before running the this command. Failing tests will provide helpful error messages that you can use to debug your code — read them closely for hints!

**Comment by jenmyers** [comment]
Resolved.
