### ISSUE TITLE
Problem with Hyperlink

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/well-formed-html-document-lab#8]
Hello! The hyperlink on the part of the document that says "viewing HTML pages in the Learn IDE" doesn't work.

Instead of linking to "http://help.learn.co/the-learn-ide/common-ide-questions/viewing-html-pages-in-the-learn-ide", it only links to "http://help.learn.co/the-learn-ide/common-ide-questions/viewing-". 

Somehow, the rest of that link ("html-pages-in-the-learn-ide") wound up at the bottom of the document itself. Here is a picture of what I'm talking about:

![well-formed html document lab](https://user-images.githubusercontent.com/38870640/43289634-6b530ea0-90e0-11e8-8dcb-bcbd82225af6.gif)

Thanks for looking into this!
Sdcrouse

**Comment by drakeltheryuujin** [comment]
Looks like it's been fixed. Thanks!
